# -*- coding: utf-8 -*-
"""DadosCovidBr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OvFCRDGy9_x2y75ph3_lpGo3WIVS-dea
"""

import pandas as pd
import plotly.express as px
import streamlit as st

# Lendo o Dataset
df = pd.read_csv('https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv')


#Alterando os nomes da colunas
df = df.rename(columns={'newDeaths': 'Novos óbitos','newCases': 'Novos casos','deaths_per_100k_inhabitants': 'Óbitos por 100 mil habitantes','totalCases_per_100k_inhabitants':'Casos por 100 mil habitantes'})

#Estados selecionados
#state = 'MS'
estados = list(df['state'].unique())
state = st.sidebar.selectbox('Selecione uma Unidade da Federação', estados)

# Seleção da coluna
#column = 'Casos por 100 mil habitantes'
colunas = ['Novos óbitos','Novos casos','Óbitos por 100 mil habitantes','Casos por 100 mil habitantes']
column = st.sidebar.selectbox('Qual tipo de informação?', colunas)

# Seleção das linhas que pertencem ao estado
df = df[df['state'] == state]

fig = px.line(df, x='date', y=column, title=column + ' - ' + state)
fig.update_layout( xaxis_title='Data', yaxis_title=column.upper(), title = {'x':0.5})

st.title('Dados do Covid do Brasil')
st.write('Nessa aplicação o usuário pode escolher a informações do Covid')

st.plotly_chart(fig, use_container_width=True)

st.caption('Os dados foram obtidos deste site: https://github.com/wcota/covid19br')
